<?xml version="1.0" encoding="utf-8"?><Database Name="LySeek" Class="DBToolsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Ranjbaran;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RanjbaranConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.spGetCount" Method="spGetCount">
    <Parameter Name="TableName" Parameter="tableName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="WhereCond" Parameter="whereCond" Type="System.String" DbType="NVarChar(1000)" />
    <ElementType Name="spGetCountResult">
      <Column Name="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>