<?xml version="1.0" encoding="utf-8"?><Database Name="Ranjbaran" Class="GalleriesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Ranjbaran;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RanjbaranConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Galleries" Member="Galleries">
    <Type Name="Galleries">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SmallPicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vGalleries" Member="vGalleries">
    <Type Name="vGalleries">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SmallPicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>