#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranjbaran.Old_App_Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ranjbaran")]
	public partial class OrdersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOrders(Orders instance);
    partial void UpdateOrders(Orders instance);
    partial void DeleteOrders(Orders instance);
    partial void InsertOrderProducts(OrderProducts instance);
    partial void UpdateOrderProducts(OrderProducts instance);
    partial void DeleteOrderProducts(OrderProducts instance);
    #endregion
		
		public OrdersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RanjbaranConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrdersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrdersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrdersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrdersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Orders> Orders
		{
			get
			{
				return this.GetTable<Orders>();
			}
		}
		
		public System.Data.Linq.Table<OrderProducts> OrderProducts
		{
			get
			{
				return this.GetTable<OrderProducts>();
			}
		}
		
		public System.Data.Linq.Table<vOrderProducts> vOrderProducts
		{
			get
			{
				return this.GetTable<vOrderProducts>();
			}
		}
		
		public System.Data.Linq.Table<vOrders> vOrders
		{
			get
			{
				return this.GetTable<vOrders>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orders")]
	public partial class Orders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _ID;
		
		private string _FullName;
		
		private System.Nullable<int> _HCGenderCode;
		
		private System.Nullable<int> _ProvinceCode;
		
		private System.Nullable<int> _CityCode;
		
		private string _Tel;
		
		private string _CellPhone;
		
		private string _Email;
		
		private string _PostalCode;
		
		private string _Address;
		
		private string _Description;
		
		private System.Nullable<int> _HCSendTypeCode;
		
		private System.Nullable<int> _Discount;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _SendPrice;
		
		private System.Nullable<int> _OtherCosts;
		
		private System.Nullable<int> _TotalProductPrice;
		
		private System.Nullable<int> _TotalOrderCost;
		
		private System.Nullable<int> _HCOrderStatusCode;
		
		private System.Nullable<int> _UserCode;
		
		private string _PayeganOrderCode;
		
		private string _PostOrderCode;
		
		private System.Nullable<int> _HCOrderPayStatusCode;
		
		private System.Nullable<int> _HCPayMethodCode;
		
		private System.Nullable<int> _BuyCost;
		
		private System.Nullable<int> _RefUserCode;
		
		private System.Nullable<bool> _RefPayed;
		
		private System.Nullable<int> _UserTransactionCode;
		
		private EntitySet<OrderProducts> _OrderProducts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnHCGenderCodeChanging(System.Nullable<int> value);
    partial void OnHCGenderCodeChanged();
    partial void OnProvinceCodeChanging(System.Nullable<int> value);
    partial void OnProvinceCodeChanged();
    partial void OnCityCodeChanging(System.Nullable<int> value);
    partial void OnCityCodeChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnCellPhoneChanging(string value);
    partial void OnCellPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnHCSendTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCSendTypeCodeChanged();
    partial void OnDiscountChanging(System.Nullable<int> value);
    partial void OnDiscountChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnSendPriceChanging(System.Nullable<int> value);
    partial void OnSendPriceChanged();
    partial void OnOtherCostsChanging(System.Nullable<int> value);
    partial void OnOtherCostsChanged();
    partial void OnTotalProductPriceChanging(System.Nullable<int> value);
    partial void OnTotalProductPriceChanged();
    partial void OnTotalOrderCostChanging(System.Nullable<int> value);
    partial void OnTotalOrderCostChanged();
    partial void OnHCOrderStatusCodeChanging(System.Nullable<int> value);
    partial void OnHCOrderStatusCodeChanged();
    partial void OnUserCodeChanging(System.Nullable<int> value);
    partial void OnUserCodeChanged();
    partial void OnPayeganOrderCodeChanging(string value);
    partial void OnPayeganOrderCodeChanged();
    partial void OnPostOrderCodeChanging(string value);
    partial void OnPostOrderCodeChanged();
    partial void OnHCOrderPayStatusCodeChanging(System.Nullable<int> value);
    partial void OnHCOrderPayStatusCodeChanged();
    partial void OnHCPayMethodCodeChanging(System.Nullable<int> value);
    partial void OnHCPayMethodCodeChanged();
    partial void OnBuyCostChanging(System.Nullable<int> value);
    partial void OnBuyCostChanged();
    partial void OnRefUserCodeChanging(System.Nullable<int> value);
    partial void OnRefUserCodeChanged();
    partial void OnRefPayedChanging(System.Nullable<bool> value);
    partial void OnRefPayedChanged();
    partial void OnUserTransactionCodeChanging(System.Nullable<int> value);
    partial void OnUserTransactionCodeChanged();
    #endregion
		
		public Orders()
		{
			this._OrderProducts = new EntitySet<OrderProducts>(new Action<OrderProducts>(this.attach_OrderProducts), new Action<OrderProducts>(this.detach_OrderProducts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCGenderCode", DbType="Int")]
		public System.Nullable<int> HCGenderCode
		{
			get
			{
				return this._HCGenderCode;
			}
			set
			{
				if ((this._HCGenderCode != value))
				{
					this.OnHCGenderCodeChanging(value);
					this.SendPropertyChanging();
					this._HCGenderCode = value;
					this.SendPropertyChanged("HCGenderCode");
					this.OnHCGenderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceCode", DbType="Int")]
		public System.Nullable<int> ProvinceCode
		{
			get
			{
				return this._ProvinceCode;
			}
			set
			{
				if ((this._ProvinceCode != value))
				{
					this.OnProvinceCodeChanging(value);
					this.SendPropertyChanging();
					this._ProvinceCode = value;
					this.SendPropertyChanged("ProvinceCode");
					this.OnProvinceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="Int")]
		public System.Nullable<int> CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this.OnCityCodeChanging(value);
					this.SendPropertyChanging();
					this._CityCode = value;
					this.SendPropertyChanged("CityCode");
					this.OnCityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(100)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="NVarChar(100)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this.OnCellPhoneChanging(value);
					this.SendPropertyChanging();
					this._CellPhone = value;
					this.SendPropertyChanged("CellPhone");
					this.OnCellPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(100)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSendTypeCode", DbType="Int")]
		public System.Nullable<int> HCSendTypeCode
		{
			get
			{
				return this._HCSendTypeCode;
			}
			set
			{
				if ((this._HCSendTypeCode != value))
				{
					this.OnHCSendTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCSendTypeCode = value;
					this.SendPropertyChanged("HCSendTypeCode");
					this.OnHCSendTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Int")]
		public System.Nullable<int> Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this.OnDiscountChanging(value);
					this.SendPropertyChanging();
					this._Discount = value;
					this.SendPropertyChanged("Discount");
					this.OnDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendPrice", DbType="Int")]
		public System.Nullable<int> SendPrice
		{
			get
			{
				return this._SendPrice;
			}
			set
			{
				if ((this._SendPrice != value))
				{
					this.OnSendPriceChanging(value);
					this.SendPropertyChanging();
					this._SendPrice = value;
					this.SendPropertyChanged("SendPrice");
					this.OnSendPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherCosts", DbType="Int")]
		public System.Nullable<int> OtherCosts
		{
			get
			{
				return this._OtherCosts;
			}
			set
			{
				if ((this._OtherCosts != value))
				{
					this.OnOtherCostsChanging(value);
					this.SendPropertyChanging();
					this._OtherCosts = value;
					this.SendPropertyChanged("OtherCosts");
					this.OnOtherCostsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalProductPrice", DbType="Int")]
		public System.Nullable<int> TotalProductPrice
		{
			get
			{
				return this._TotalProductPrice;
			}
			set
			{
				if ((this._TotalProductPrice != value))
				{
					this.OnTotalProductPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalProductPrice = value;
					this.SendPropertyChanged("TotalProductPrice");
					this.OnTotalProductPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalOrderCost", DbType="Int")]
		public System.Nullable<int> TotalOrderCost
		{
			get
			{
				return this._TotalOrderCost;
			}
			set
			{
				if ((this._TotalOrderCost != value))
				{
					this.OnTotalOrderCostChanging(value);
					this.SendPropertyChanging();
					this._TotalOrderCost = value;
					this.SendPropertyChanged("TotalOrderCost");
					this.OnTotalOrderCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCOrderStatusCode", DbType="Int")]
		public System.Nullable<int> HCOrderStatusCode
		{
			get
			{
				return this._HCOrderStatusCode;
			}
			set
			{
				if ((this._HCOrderStatusCode != value))
				{
					this.OnHCOrderStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCOrderStatusCode = value;
					this.SendPropertyChanged("HCOrderStatusCode");
					this.OnHCOrderStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayeganOrderCode", DbType="VarChar(50)")]
		public string PayeganOrderCode
		{
			get
			{
				return this._PayeganOrderCode;
			}
			set
			{
				if ((this._PayeganOrderCode != value))
				{
					this.OnPayeganOrderCodeChanging(value);
					this.SendPropertyChanging();
					this._PayeganOrderCode = value;
					this.SendPropertyChanged("PayeganOrderCode");
					this.OnPayeganOrderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOrderCode", DbType="VarChar(50)")]
		public string PostOrderCode
		{
			get
			{
				return this._PostOrderCode;
			}
			set
			{
				if ((this._PostOrderCode != value))
				{
					this.OnPostOrderCodeChanging(value);
					this.SendPropertyChanging();
					this._PostOrderCode = value;
					this.SendPropertyChanged("PostOrderCode");
					this.OnPostOrderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCOrderPayStatusCode", DbType="Int")]
		public System.Nullable<int> HCOrderPayStatusCode
		{
			get
			{
				return this._HCOrderPayStatusCode;
			}
			set
			{
				if ((this._HCOrderPayStatusCode != value))
				{
					this.OnHCOrderPayStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCOrderPayStatusCode = value;
					this.SendPropertyChanged("HCOrderPayStatusCode");
					this.OnHCOrderPayStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPayMethodCode", DbType="Int")]
		public System.Nullable<int> HCPayMethodCode
		{
			get
			{
				return this._HCPayMethodCode;
			}
			set
			{
				if ((this._HCPayMethodCode != value))
				{
					this.OnHCPayMethodCodeChanging(value);
					this.SendPropertyChanging();
					this._HCPayMethodCode = value;
					this.SendPropertyChanged("HCPayMethodCode");
					this.OnHCPayMethodCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyCost", DbType="Int")]
		public System.Nullable<int> BuyCost
		{
			get
			{
				return this._BuyCost;
			}
			set
			{
				if ((this._BuyCost != value))
				{
					this.OnBuyCostChanging(value);
					this.SendPropertyChanging();
					this._BuyCost = value;
					this.SendPropertyChanged("BuyCost");
					this.OnBuyCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefUserCode", DbType="Int")]
		public System.Nullable<int> RefUserCode
		{
			get
			{
				return this._RefUserCode;
			}
			set
			{
				if ((this._RefUserCode != value))
				{
					this.OnRefUserCodeChanging(value);
					this.SendPropertyChanging();
					this._RefUserCode = value;
					this.SendPropertyChanged("RefUserCode");
					this.OnRefUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefPayed", DbType="Bit")]
		public System.Nullable<bool> RefPayed
		{
			get
			{
				return this._RefPayed;
			}
			set
			{
				if ((this._RefPayed != value))
				{
					this.OnRefPayedChanging(value);
					this.SendPropertyChanging();
					this._RefPayed = value;
					this.SendPropertyChanged("RefPayed");
					this.OnRefPayedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTransactionCode", DbType="Int")]
		public System.Nullable<int> UserTransactionCode
		{
			get
			{
				return this._UserTransactionCode;
			}
			set
			{
				if ((this._UserTransactionCode != value))
				{
					this.OnUserTransactionCodeChanging(value);
					this.SendPropertyChanging();
					this._UserTransactionCode = value;
					this.SendPropertyChanged("UserTransactionCode");
					this.OnUserTransactionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Orders_OrderProducts", Storage="_OrderProducts", ThisKey="Code", OtherKey="OrderCode")]
		public EntitySet<OrderProducts> OrderProducts
		{
			get
			{
				return this._OrderProducts;
			}
			set
			{
				this._OrderProducts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OrderProducts(OrderProducts entity)
		{
			this.SendPropertyChanging();
			entity.Orders = this;
		}
		
		private void detach_OrderProducts(OrderProducts entity)
		{
			this.SendPropertyChanging();
			entity.Orders = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderProducts")]
	public partial class OrderProducts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _OrderCode;
		
		private System.Nullable<int> _ProductCode;
		
		private System.Nullable<int> _Weight;
		
		private System.Nullable<int> _ProductPrice;
		
		private System.Nullable<int> _SendPrice;
		
		private System.Nullable<int> _HCProductOrderStatusCode;
		
		private System.Nullable<int> _ItemCount;
		
		private EntityRef<Orders> _Orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnOrderCodeChanging(System.Nullable<int> value);
    partial void OnOrderCodeChanged();
    partial void OnProductCodeChanging(System.Nullable<int> value);
    partial void OnProductCodeChanged();
    partial void OnWeightChanging(System.Nullable<int> value);
    partial void OnWeightChanged();
    partial void OnProductPriceChanging(System.Nullable<int> value);
    partial void OnProductPriceChanged();
    partial void OnSendPriceChanging(System.Nullable<int> value);
    partial void OnSendPriceChanged();
    partial void OnHCProductOrderStatusCodeChanging(System.Nullable<int> value);
    partial void OnHCProductOrderStatusCodeChanged();
    partial void OnItemCountChanging(System.Nullable<int> value);
    partial void OnItemCountChanged();
    #endregion
		
		public OrderProducts()
		{
			this._Orders = default(EntityRef<Orders>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderCode", DbType="Int")]
		public System.Nullable<int> OrderCode
		{
			get
			{
				return this._OrderCode;
			}
			set
			{
				if ((this._OrderCode != value))
				{
					if (this._Orders.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrderCodeChanging(value);
					this.SendPropertyChanging();
					this._OrderCode = value;
					this.SendPropertyChanged("OrderCode");
					this.OnOrderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this.OnProductCodeChanging(value);
					this.SendPropertyChanging();
					this._ProductCode = value;
					this.SendPropertyChanged("ProductCode");
					this.OnProductCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int")]
		public System.Nullable<int> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductPrice", DbType="Int")]
		public System.Nullable<int> ProductPrice
		{
			get
			{
				return this._ProductPrice;
			}
			set
			{
				if ((this._ProductPrice != value))
				{
					this.OnProductPriceChanging(value);
					this.SendPropertyChanging();
					this._ProductPrice = value;
					this.SendPropertyChanged("ProductPrice");
					this.OnProductPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendPrice", DbType="Int")]
		public System.Nullable<int> SendPrice
		{
			get
			{
				return this._SendPrice;
			}
			set
			{
				if ((this._SendPrice != value))
				{
					this.OnSendPriceChanging(value);
					this.SendPropertyChanging();
					this._SendPrice = value;
					this.SendPropertyChanged("SendPrice");
					this.OnSendPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCProductOrderStatusCode", DbType="Int")]
		public System.Nullable<int> HCProductOrderStatusCode
		{
			get
			{
				return this._HCProductOrderStatusCode;
			}
			set
			{
				if ((this._HCProductOrderStatusCode != value))
				{
					this.OnHCProductOrderStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCProductOrderStatusCode = value;
					this.SendPropertyChanged("HCProductOrderStatusCode");
					this.OnHCProductOrderStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCount", DbType="Int")]
		public System.Nullable<int> ItemCount
		{
			get
			{
				return this._ItemCount;
			}
			set
			{
				if ((this._ItemCount != value))
				{
					this.OnItemCountChanging(value);
					this.SendPropertyChanging();
					this._ItemCount = value;
					this.SendPropertyChanged("ItemCount");
					this.OnItemCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Orders_OrderProducts", Storage="_Orders", ThisKey="OrderCode", OtherKey="Code", IsForeignKey=true)]
		public Orders Orders
		{
			get
			{
				return this._Orders.Entity;
			}
			set
			{
				Orders previousValue = this._Orders.Entity;
				if (((previousValue != value) 
							|| (this._Orders.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Orders.Entity = null;
						previousValue.OrderProducts.Remove(this);
					}
					this._Orders.Entity = value;
					if ((value != null))
					{
						value.OrderProducts.Add(this);
						this._OrderCode = value.Code;
					}
					else
					{
						this._OrderCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("Orders");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vOrderProducts")]
	public partial class vOrderProducts
	{
		
		private int _Code;
		
		private System.Nullable<int> _OrderCode;
		
		private string _ProductName;
		
		private string _ProductStatus;
		
		private System.Nullable<int> _Weight;
		
		private System.Nullable<int> _ProductPrice;
		
		private System.Nullable<int> _ItemCount;
		
		private string _EnTitle;
		
		private System.Nullable<int> _ProductCode;
		
		public vOrderProducts()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderCode", DbType="Int")]
		public System.Nullable<int> OrderCode
		{
			get
			{
				return this._OrderCode;
			}
			set
			{
				if ((this._OrderCode != value))
				{
					this._OrderCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(500)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductStatus", DbType="NVarChar(500)")]
		public string ProductStatus
		{
			get
			{
				return this._ProductStatus;
			}
			set
			{
				if ((this._ProductStatus != value))
				{
					this._ProductStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int")]
		public System.Nullable<int> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductPrice", DbType="Int")]
		public System.Nullable<int> ProductPrice
		{
			get
			{
				return this._ProductPrice;
			}
			set
			{
				if ((this._ProductPrice != value))
				{
					this._ProductPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCount", DbType="Int")]
		public System.Nullable<int> ItemCount
		{
			get
			{
				return this._ItemCount;
			}
			set
			{
				if ((this._ItemCount != value))
				{
					this._ItemCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnTitle", DbType="NVarChar(500)")]
		public string EnTitle
		{
			get
			{
				return this._EnTitle;
			}
			set
			{
				if ((this._EnTitle != value))
				{
					this._EnTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="Int")]
		public System.Nullable<int> ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vOrders")]
	public partial class vOrders
	{
		
		private int _Code;
		
		private string _CDate;
		
		private string _FullName;
		
		private string _CellPhone;
		
		private string _Province;
		
		private string _City;
		
		private string _OrderStatus;
		
		private System.Nullable<int> _HCOrderStatusCode;
		
		private System.Nullable<int> _SendPrice;
		
		private System.Nullable<int> _OtherCosts;
		
		private System.Nullable<int> _TotalOrderCost;
		
		private System.Nullable<int> _BuyCost;
		
		private string _SendType;
		
		private string _PostalCode;
		
		private string _Email;
		
		private string _Address;
		
		private string _Description;
		
		private string _PostOrderCode;
		
		private string _PayeganOrderCode;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _ID;
		
		private System.Nullable<int> _UserCode;
		
		private System.Nullable<int> _UserTransactionCode;
		
		private System.Nullable<int> _HCTransStatusCode;
		
		private System.Nullable<int> _HCPayMethodCode;
		
		private string _OrderPayStatus;
		
		private string _Tel;
		
		public vOrders()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDate", DbType="VarChar(10)")]
		public string CDate
		{
			get
			{
				return this._CDate;
			}
			set
			{
				if ((this._CDate != value))
				{
					this._CDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="NVarChar(100)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this._CellPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(100)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this._Province = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderStatus", DbType="NVarChar(500)")]
		public string OrderStatus
		{
			get
			{
				return this._OrderStatus;
			}
			set
			{
				if ((this._OrderStatus != value))
				{
					this._OrderStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCOrderStatusCode", DbType="Int")]
		public System.Nullable<int> HCOrderStatusCode
		{
			get
			{
				return this._HCOrderStatusCode;
			}
			set
			{
				if ((this._HCOrderStatusCode != value))
				{
					this._HCOrderStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendPrice", DbType="Int")]
		public System.Nullable<int> SendPrice
		{
			get
			{
				return this._SendPrice;
			}
			set
			{
				if ((this._SendPrice != value))
				{
					this._SendPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherCosts", DbType="Int")]
		public System.Nullable<int> OtherCosts
		{
			get
			{
				return this._OtherCosts;
			}
			set
			{
				if ((this._OtherCosts != value))
				{
					this._OtherCosts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalOrderCost", DbType="Int")]
		public System.Nullable<int> TotalOrderCost
		{
			get
			{
				return this._TotalOrderCost;
			}
			set
			{
				if ((this._TotalOrderCost != value))
				{
					this._TotalOrderCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyCost", DbType="Int")]
		public System.Nullable<int> BuyCost
		{
			get
			{
				return this._BuyCost;
			}
			set
			{
				if ((this._BuyCost != value))
				{
					this._BuyCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendType", DbType="NVarChar(500)")]
		public string SendType
		{
			get
			{
				return this._SendType;
			}
			set
			{
				if ((this._SendType != value))
				{
					this._SendType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(100)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this._PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOrderCode", DbType="VarChar(50)")]
		public string PostOrderCode
		{
			get
			{
				return this._PostOrderCode;
			}
			set
			{
				if ((this._PostOrderCode != value))
				{
					this._PostOrderCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayeganOrderCode", DbType="VarChar(50)")]
		public string PayeganOrderCode
		{
			get
			{
				return this._PayeganOrderCode;
			}
			set
			{
				if ((this._PayeganOrderCode != value))
				{
					this._PayeganOrderCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTransactionCode", DbType="Int")]
		public System.Nullable<int> UserTransactionCode
		{
			get
			{
				return this._UserTransactionCode;
			}
			set
			{
				if ((this._UserTransactionCode != value))
				{
					this._UserTransactionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCTransStatusCode", DbType="Int")]
		public System.Nullable<int> HCTransStatusCode
		{
			get
			{
				return this._HCTransStatusCode;
			}
			set
			{
				if ((this._HCTransStatusCode != value))
				{
					this._HCTransStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPayMethodCode", DbType="Int")]
		public System.Nullable<int> HCPayMethodCode
		{
			get
			{
				return this._HCPayMethodCode;
			}
			set
			{
				if ((this._HCPayMethodCode != value))
				{
					this._HCPayMethodCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderPayStatus", DbType="NVarChar(500)")]
		public string OrderPayStatus
		{
			get
			{
				return this._OrderPayStatus;
			}
			set
			{
				if ((this._OrderPayStatus != value))
				{
					this._OrderPayStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(100)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
