<?xml version="1.0" encoding="utf-8"?><Database Name="Ranjbaran" Class="ProductsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Ranjbaran;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RanjbaranConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProductCats" Member="ProductCats">
    <Type Name="ProductCat">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MasterCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ProductCat_ProductCat" Member="ProductCats" ThisKey="Code" OtherKey="MasterCode" Type="ProductCat" />
      <Association Name="ProductCat_ProductCat" Member="ProductCat1" ThisKey="MasterCode" OtherKey="Code" Type="ProductCat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductComments" Member="ProductComments">
    <Type Name="ProductComments">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CommentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCCommentStatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminComment" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Association Name="Products_ProductComments" Member="Products" ThisKey="ProductCode" OtherKey="Code" Type="Products" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductEditUsers" Member="ProductEditUsers">
    <Type Name="ProductEditUsers">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditUserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductPictures" Member="ProductPictures">
    <Type Name="ProductPictures">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SmallPicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Products_ProductPictures" Member="Products" ThisKey="ProductCode" OtherKey="Code" Type="Products" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductPriceLogs" Member="ProductPriceLogs">
    <Type Name="ProductPriceLogs">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Products_ProductPriceLogs" Member="Products" ThisKey="ProductCode" OtherKey="Code" Type="Products" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductRelatedPros" Member="ProductRelatedPros">
    <Type Name="ProductRelatedPros">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelatedProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Products_ProductRelatedPros" Member="Product" ThisKey="ProductCode" OtherKey="Code" Type="Products" IsForeignKey="true" />
      <Association Name="Products_ProductRelatedPros1" Member="Products" ThisKey="RelatedProductCode" OtherKey="Code" Type="Products" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Products">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FaTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Special" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsNew" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDiscount" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMostSold" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SmallPicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LargePicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MarketPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendPishtazPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendSefareshiPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductCatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InternalCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StarCount" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViewNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HCProductAvailabilityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="Products_ProductComments" Member="ProductComments" ThisKey="Code" OtherKey="ProductCode" Type="ProductComments" />
      <Association Name="Products_ProductPictures" Member="ProductPictures" ThisKey="Code" OtherKey="ProductCode" Type="ProductPictures" />
      <Association Name="Products_ProductPriceLogs" Member="ProductPriceLogs" ThisKey="Code" OtherKey="ProductCode" Type="ProductPriceLogs" />
      <Association Name="Products_ProductRelatedPros" Member="ProductRelatedPros" ThisKey="Code" OtherKey="ProductCode" Type="ProductRelatedPros" />
      <Association Name="Products_ProductRelatedPros1" Member="ProductRelatedPros1" ThisKey="Code" OtherKey="RelatedProductCode" Type="ProductRelatedPros" />
      <Association Name="Products_ProductVisits" Member="ProductVisits" ThisKey="Code" OtherKey="ProductCode" Type="ProductVisits" />
    </Type>
  </Table>
  <Table Name="dbo.ProductVisits" Member="ProductVisits">
    <Type Name="ProductVisits">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VisitDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Products_ProductVisits" Member="Products" ThisKey="ProductCode" OtherKey="Code" Type="Products" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vProductCats" Member="vProductCats">
    <Type Name="vProductCats">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MasterCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vProductComments" Member="vProductComments">
    <Type Name="vProductComments">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SenderEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminComment" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vProductEditUsers" Member="vProductEditUsers">
    <Type Name="vProductEditUsers">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vProductPictures" Member="vProductPictures">
    <Type Name="vProductPictures">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vProductRelatedPros" Member="vProductRelatedPros">
    <Type Name="vProductRelatedPros">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelatedProduct" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SmallPicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RelatedProductCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vProducts" Member="vProducts">
    <Type Name="vProducts">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FaTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CatTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViewNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LargePicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ProductCatCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InternalCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SmallPicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HCProductAvailabilityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Availabality" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Special" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MarketPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnTitle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsNew" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDiscount" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsMostSold" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>