<?xml version="1.0" encoding="utf-8"?><Database Name="Ranjbaran" Class="PublicationsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Ranjbaran;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RanjbaranConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PublicationGroups" Member="PublicationGroups">
    <Type Name="PublicationGroups">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PublicationCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Publication_PublicationGroups" Member="Publications" Storage="_Publication" ThisKey="PublicationCode" OtherKey="Code" Type="Publications" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vPublicationGroups" Member="vPublicationGroups">
    <Type Name="vPublicationGroups">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublicationCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Publications" Member="Publications">
    <Type Name="Publications">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="SmallPic" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LargePic" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PDFFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Entesharat" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PublicationTurn" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Ciculation" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Publication_PublicationGroups" Member="PublicationGroups" ThisKey="Code" OtherKey="PublicationCode" Type="PublicationGroups" />
    </Type>
  </Table>
  <Table Name="dbo.vPublications" Member="vPublications">
    <Type Name="vPublications">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PublicationTurn" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ShowOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="SmallPic" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LargePic" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PDFFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Entesharat" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ciculation" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>