<?xml version="1.0" encoding="utf-8"?><Database Name="Ranjbaran" Class="StudyInfosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Ranjbaran;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RanjbaranConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StudyInfos" Member="StudyInfos">
    <Type Name="StudyInfos">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HCStudyFieldCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCGradeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vStudyInfos" Member="vStudyInfos">
    <Type Name="vStudyInfos">
      <Column Name="Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HCStudyField" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HCGrade" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HCStudyFieldCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCGradeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GradeVal" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ShowOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vStudyInfos2" Member="vStudyInfos2s">
    <Type Name="vStudyInfos2">
      <Column Name="Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HCStudyField" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HCGrade" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HCGradeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GradeVal" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ShowOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCStudyFieldCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>