#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranjbaran.Old_App_Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ranjbaran")]
	public partial class UsersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccessGroups(AccessGroups instance);
    partial void UpdateAccessGroups(AccessGroups instance);
    partial void DeleteAccessGroups(AccessGroups instance);
    partial void InsertResources(Resources instance);
    partial void UpdateResources(Resources instance);
    partial void DeleteResources(Resources instance);
    partial void InsertUserGroups(UserGroups instance);
    partial void UpdateUserGroups(UserGroups instance);
    partial void DeleteUserGroups(UserGroups instance);
    partial void InsertGroupResources(GroupResources instance);
    partial void UpdateGroupResources(GroupResources instance);
    partial void DeleteGroupResources(GroupResources instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    partial void InsertForgotPasswords(ForgotPasswords instance);
    partial void UpdateForgotPasswords(ForgotPasswords instance);
    partial void DeleteForgotPasswords(ForgotPasswords instance);
    partial void InsertUserAddresses(UserAddresses instance);
    partial void UpdateUserAddresses(UserAddresses instance);
    partial void DeleteUserAddresses(UserAddresses instance);
    partial void InsertUserTransactions(UserTransactions instance);
    partial void UpdateUserTransactions(UserTransactions instance);
    partial void DeleteUserTransactions(UserTransactions instance);
    #endregion
		
		public UsersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RanjbaranConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vUsers> vUsers
		{
			get
			{
				return this.GetTable<vUsers>();
			}
		}
		
		public System.Data.Linq.Table<AccessGroups> AccessGroups
		{
			get
			{
				return this.GetTable<AccessGroups>();
			}
		}
		
		public System.Data.Linq.Table<Resources> Resources
		{
			get
			{
				return this.GetTable<Resources>();
			}
		}
		
		public System.Data.Linq.Table<UserGroups> UserGroups
		{
			get
			{
				return this.GetTable<UserGroups>();
			}
		}
		
		public System.Data.Linq.Table<GroupResources> GroupResources
		{
			get
			{
				return this.GetTable<GroupResources>();
			}
		}
		
		public System.Data.Linq.Table<vAccessGroups> vAccessGroups
		{
			get
			{
				return this.GetTable<vAccessGroups>();
			}
		}
		
		public System.Data.Linq.Table<vGroupResources> vGroupResources
		{
			get
			{
				return this.GetTable<vGroupResources>();
			}
		}
		
		public System.Data.Linq.Table<vUserGroups> vUserGroups
		{
			get
			{
				return this.GetTable<vUserGroups>();
			}
		}
		
		public System.Data.Linq.Table<vResources> vResources
		{
			get
			{
				return this.GetTable<vResources>();
			}
		}
		
		public System.Data.Linq.Table<vUserAccess> vUserAccesses
		{
			get
			{
				return this.GetTable<vUserAccess>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
		
		public System.Data.Linq.Table<ForgotPasswords> ForgotPasswords
		{
			get
			{
				return this.GetTable<ForgotPasswords>();
			}
		}
		
		public System.Data.Linq.Table<vValidForgotPasswords> vValidForgotPasswords
		{
			get
			{
				return this.GetTable<vValidForgotPasswords>();
			}
		}
		
		public System.Data.Linq.Table<vUserTransactions> vUserTransactions
		{
			get
			{
				return this.GetTable<vUserTransactions>();
			}
		}
		
		public System.Data.Linq.Table<vUserAddresses> vUserAddresses
		{
			get
			{
				return this.GetTable<vUserAddresses>();
			}
		}
		
		public System.Data.Linq.Table<UserAddresses> UserAddresses
		{
			get
			{
				return this.GetTable<UserAddresses>();
			}
		}
		
		public System.Data.Linq.Table<UserTransactions> UserTransactions
		{
			get
			{
				return this.GetTable<UserTransactions>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetMultipleAccess")]
		public ISingleResult<sp_GetMultipleAccessResult> sp_GetMultipleAccess([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> paramAccessTypeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> paramGroupCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> paramMasterCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), paramAccessTypeCode, paramGroupCode, paramMasterCode);
			return ((ISingleResult<sp_GetMultipleAccessResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUsers")]
	public partial class vUsers
	{
		
		private int _Code;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _StudyFieldName;
		
		private string _GenderName;
		
		private string _ContactNumber;
		
		public vUsers()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudyFieldName", DbType="NVarChar(500)")]
		public string StudyFieldName
		{
			get
			{
				return this._StudyFieldName;
			}
			set
			{
				if ((this._StudyFieldName != value))
				{
					this._StudyFieldName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderName", DbType="NVarChar(500)")]
		public string GenderName
		{
			get
			{
				return this._GenderName;
			}
			set
			{
				if ((this._GenderName != value))
				{
					this._GenderName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(50)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccessGroups")]
	public partial class AccessGroups : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Name;
		
		private EntitySet<UserGroups> _UserGroups;
		
		private EntitySet<GroupResources> _GroupResources;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public AccessGroups()
		{
			this._UserGroups = new EntitySet<UserGroups>(new Action<UserGroups>(this.attach_UserGroups), new Action<UserGroups>(this.detach_UserGroups));
			this._GroupResources = new EntitySet<GroupResources>(new Action<GroupResources>(this.attach_GroupResources), new Action<GroupResources>(this.detach_GroupResources));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AccessGroups_UserGroups", Storage="_UserGroups", ThisKey="Code", OtherKey="GroupCode")]
		public EntitySet<UserGroups> UserGroups
		{
			get
			{
				return this._UserGroups;
			}
			set
			{
				this._UserGroups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AccessGroups_GroupResources", Storage="_GroupResources", ThisKey="Code", OtherKey="GroupCode")]
		public EntitySet<GroupResources> GroupResources
		{
			get
			{
				return this._GroupResources;
			}
			set
			{
				this._GroupResources.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserGroups(UserGroups entity)
		{
			this.SendPropertyChanging();
			entity.AccessGroups = this;
		}
		
		private void detach_UserGroups(UserGroups entity)
		{
			this.SendPropertyChanging();
			entity.AccessGroups = null;
		}
		
		private void attach_GroupResources(GroupResources entity)
		{
			this.SendPropertyChanging();
			entity.AccessGroups = this;
		}
		
		private void detach_GroupResources(GroupResources entity)
		{
			this.SendPropertyChanging();
			entity.AccessGroups = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resources")]
	public partial class Resources : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _Name;
		
		private string _EngName;
		
		private System.Nullable<int> _HCResourceTypeCode;
		
		private System.Nullable<int> _MasterCode;
		
		private string _EditPath;
		
		private string _BaseID;
		
		private System.Nullable<int> _BasicAccessType;
		
		private string _ResName;
		
		private System.Nullable<int> _Ordering;
		
		private EntitySet<Resources> _Resources1;
		
		private EntitySet<GroupResources> _GroupResources;
		
		private EntityRef<Resources> _Resource1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEngNameChanging(string value);
    partial void OnEngNameChanged();
    partial void OnHCResourceTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCResourceTypeCodeChanged();
    partial void OnMasterCodeChanging(System.Nullable<int> value);
    partial void OnMasterCodeChanged();
    partial void OnEditPathChanging(string value);
    partial void OnEditPathChanged();
    partial void OnBaseIDChanging(string value);
    partial void OnBaseIDChanged();
    partial void OnBasicAccessTypeChanging(System.Nullable<int> value);
    partial void OnBasicAccessTypeChanged();
    partial void OnResNameChanging(string value);
    partial void OnResNameChanged();
    partial void OnOrderingChanging(System.Nullable<int> value);
    partial void OnOrderingChanged();
    #endregion
		
		public Resources()
		{
			this._Resources1 = new EntitySet<Resources>(new Action<Resources>(this.attach_Resources1), new Action<Resources>(this.detach_Resources1));
			this._GroupResources = new EntitySet<GroupResources>(new Action<GroupResources>(this.attach_GroupResources), new Action<GroupResources>(this.detach_GroupResources));
			this._Resource1 = default(EntityRef<Resources>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngName", DbType="NVarChar(500)")]
		public string EngName
		{
			get
			{
				return this._EngName;
			}
			set
			{
				if ((this._EngName != value))
				{
					this.OnEngNameChanging(value);
					this.SendPropertyChanging();
					this._EngName = value;
					this.SendPropertyChanged("EngName");
					this.OnEngNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCResourceTypeCode", DbType="Int")]
		public System.Nullable<int> HCResourceTypeCode
		{
			get
			{
				return this._HCResourceTypeCode;
			}
			set
			{
				if ((this._HCResourceTypeCode != value))
				{
					this.OnHCResourceTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCResourceTypeCode = value;
					this.SendPropertyChanged("HCResourceTypeCode");
					this.OnHCResourceTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCode", DbType="Int")]
		public System.Nullable<int> MasterCode
		{
			get
			{
				return this._MasterCode;
			}
			set
			{
				if ((this._MasterCode != value))
				{
					if (this._Resource1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMasterCodeChanging(value);
					this.SendPropertyChanging();
					this._MasterCode = value;
					this.SendPropertyChanged("MasterCode");
					this.OnMasterCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditPath", DbType="VarChar(200)")]
		public string EditPath
		{
			get
			{
				return this._EditPath;
			}
			set
			{
				if ((this._EditPath != value))
				{
					this.OnEditPathChanging(value);
					this.SendPropertyChanging();
					this._EditPath = value;
					this.SendPropertyChanged("EditPath");
					this.OnEditPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseID", DbType="VarChar(100)")]
		public string BaseID
		{
			get
			{
				return this._BaseID;
			}
			set
			{
				if ((this._BaseID != value))
				{
					this.OnBaseIDChanging(value);
					this.SendPropertyChanging();
					this._BaseID = value;
					this.SendPropertyChanged("BaseID");
					this.OnBaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicAccessType", DbType="Int")]
		public System.Nullable<int> BasicAccessType
		{
			get
			{
				return this._BasicAccessType;
			}
			set
			{
				if ((this._BasicAccessType != value))
				{
					this.OnBasicAccessTypeChanging(value);
					this.SendPropertyChanging();
					this._BasicAccessType = value;
					this.SendPropertyChanged("BasicAccessType");
					this.OnBasicAccessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResName", DbType="VarChar(100)")]
		public string ResName
		{
			get
			{
				return this._ResName;
			}
			set
			{
				if ((this._ResName != value))
				{
					this.OnResNameChanging(value);
					this.SendPropertyChanging();
					this._ResName = value;
					this.SendPropertyChanged("ResName");
					this.OnResNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordering", DbType="Int")]
		public System.Nullable<int> Ordering
		{
			get
			{
				return this._Ordering;
			}
			set
			{
				if ((this._Ordering != value))
				{
					this.OnOrderingChanging(value);
					this.SendPropertyChanging();
					this._Ordering = value;
					this.SendPropertyChanged("Ordering");
					this.OnOrderingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Resources_Resources", Storage="_Resources1", ThisKey="Code", OtherKey="MasterCode")]
		public EntitySet<Resources> Resources1
		{
			get
			{
				return this._Resources1;
			}
			set
			{
				this._Resources1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Resources_GroupResources", Storage="_GroupResources", ThisKey="Code", OtherKey="ResourceCode")]
		public EntitySet<GroupResources> GroupResources
		{
			get
			{
				return this._GroupResources;
			}
			set
			{
				this._GroupResources.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Resources_Resources", Storage="_Resource1", ThisKey="MasterCode", OtherKey="Code", IsForeignKey=true)]
		public Resources Resource1
		{
			get
			{
				return this._Resource1.Entity;
			}
			set
			{
				Resources previousValue = this._Resource1.Entity;
				if (((previousValue != value) 
							|| (this._Resource1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Resource1.Entity = null;
						previousValue.Resources1.Remove(this);
					}
					this._Resource1.Entity = value;
					if ((value != null))
					{
						value.Resources1.Add(this);
						this._MasterCode = value.Code;
					}
					else
					{
						this._MasterCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("Resource1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Resources1(Resources entity)
		{
			this.SendPropertyChanging();
			entity.Resource1 = this;
		}
		
		private void detach_Resources1(Resources entity)
		{
			this.SendPropertyChanging();
			entity.Resource1 = null;
		}
		
		private void attach_GroupResources(GroupResources entity)
		{
			this.SendPropertyChanging();
			entity.Resources = this;
		}
		
		private void detach_GroupResources(GroupResources entity)
		{
			this.SendPropertyChanging();
			entity.Resources = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserGroups")]
	public partial class UserGroups : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _UserCode;
		
		private System.Nullable<int> _GroupCode;
		
		private EntityRef<AccessGroups> _AccessGroups;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnUserCodeChanging(System.Nullable<int> value);
    partial void OnUserCodeChanged();
    partial void OnGroupCodeChanging(System.Nullable<int> value);
    partial void OnGroupCodeChanged();
    #endregion
		
		public UserGroups()
		{
			this._AccessGroups = default(EntityRef<AccessGroups>);
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					if (this._AccessGroups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._GroupCode = value;
					this.SendPropertyChanged("GroupCode");
					this.OnGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AccessGroups_UserGroups", Storage="_AccessGroups", ThisKey="GroupCode", OtherKey="Code", IsForeignKey=true)]
		public AccessGroups AccessGroups
		{
			get
			{
				return this._AccessGroups.Entity;
			}
			set
			{
				AccessGroups previousValue = this._AccessGroups.Entity;
				if (((previousValue != value) 
							|| (this._AccessGroups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AccessGroups.Entity = null;
						previousValue.UserGroups.Remove(this);
					}
					this._AccessGroups.Entity = value;
					if ((value != null))
					{
						value.UserGroups.Add(this);
						this._GroupCode = value.Code;
					}
					else
					{
						this._GroupCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("AccessGroups");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_UserGroups", Storage="_Users", ThisKey="UserCode", OtherKey="Code", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.UserGroups.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.UserGroups.Add(this);
						this._UserCode = value.Code;
					}
					else
					{
						this._UserCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GroupResources")]
	public partial class GroupResources : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _GroupCode;
		
		private System.Nullable<int> _ResourceCode;
		
		private System.Nullable<int> _AccessType;
		
		private EntityRef<AccessGroups> _AccessGroups;
		
		private EntityRef<Resources> _Resources;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnGroupCodeChanging(System.Nullable<int> value);
    partial void OnGroupCodeChanged();
    partial void OnResourceCodeChanging(System.Nullable<int> value);
    partial void OnResourceCodeChanged();
    partial void OnAccessTypeChanging(System.Nullable<int> value);
    partial void OnAccessTypeChanged();
    #endregion
		
		public GroupResources()
		{
			this._AccessGroups = default(EntityRef<AccessGroups>);
			this._Resources = default(EntityRef<Resources>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					if (this._AccessGroups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._GroupCode = value;
					this.SendPropertyChanged("GroupCode");
					this.OnGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceCode", DbType="Int")]
		public System.Nullable<int> ResourceCode
		{
			get
			{
				return this._ResourceCode;
			}
			set
			{
				if ((this._ResourceCode != value))
				{
					if (this._Resources.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnResourceCodeChanging(value);
					this.SendPropertyChanging();
					this._ResourceCode = value;
					this.SendPropertyChanged("ResourceCode");
					this.OnResourceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessType", DbType="Int")]
		public System.Nullable<int> AccessType
		{
			get
			{
				return this._AccessType;
			}
			set
			{
				if ((this._AccessType != value))
				{
					this.OnAccessTypeChanging(value);
					this.SendPropertyChanging();
					this._AccessType = value;
					this.SendPropertyChanged("AccessType");
					this.OnAccessTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AccessGroups_GroupResources", Storage="_AccessGroups", ThisKey="GroupCode", OtherKey="Code", IsForeignKey=true)]
		public AccessGroups AccessGroups
		{
			get
			{
				return this._AccessGroups.Entity;
			}
			set
			{
				AccessGroups previousValue = this._AccessGroups.Entity;
				if (((previousValue != value) 
							|| (this._AccessGroups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AccessGroups.Entity = null;
						previousValue.GroupResources.Remove(this);
					}
					this._AccessGroups.Entity = value;
					if ((value != null))
					{
						value.GroupResources.Add(this);
						this._GroupCode = value.Code;
					}
					else
					{
						this._GroupCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("AccessGroups");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Resources_GroupResources", Storage="_Resources", ThisKey="ResourceCode", OtherKey="Code", IsForeignKey=true, DeleteRule="CASCADE")]
		public Resources Resources
		{
			get
			{
				return this._Resources.Entity;
			}
			set
			{
				Resources previousValue = this._Resources.Entity;
				if (((previousValue != value) 
							|| (this._Resources.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Resources.Entity = null;
						previousValue.GroupResources.Remove(this);
					}
					this._Resources.Entity = value;
					if ((value != null))
					{
						value.GroupResources.Add(this);
						this._ResourceCode = value.Code;
					}
					else
					{
						this._ResourceCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("Resources");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vAccessGroups")]
	public partial class vAccessGroups
	{
		
		private int _Code;
		
		private string _Name;
		
		public vAccessGroups()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vGroupResources")]
	public partial class vGroupResources
	{
		
		private int _Code;
		
		private System.Nullable<int> _GroupCode;
		
		private string _ResourceName;
		
		private System.Nullable<int> _ResourceCode;
		
		private System.Nullable<int> _AccessType;
		
		public vGroupResources()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this._GroupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceName", DbType="NVarChar(500)")]
		public string ResourceName
		{
			get
			{
				return this._ResourceName;
			}
			set
			{
				if ((this._ResourceName != value))
				{
					this._ResourceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceCode", DbType="Int")]
		public System.Nullable<int> ResourceCode
		{
			get
			{
				return this._ResourceCode;
			}
			set
			{
				if ((this._ResourceCode != value))
				{
					this._ResourceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessType", DbType="Int")]
		public System.Nullable<int> AccessType
		{
			get
			{
				return this._AccessType;
			}
			set
			{
				if ((this._AccessType != value))
				{
					this._AccessType = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUserGroups")]
	public partial class vUserGroups
	{
		
		private int _Code;
		
		private System.Nullable<int> _UserCode;
		
		private System.Nullable<int> _GroupCode;
		
		private string _GroupName;
		
		public vUserGroups()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this._GroupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(200)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vResources")]
	public partial class vResources
	{
		
		private int _Code;
		
		private string _Name;
		
		private string _EngName;
		
		private string _BaseID;
		
		private System.Nullable<int> _MasterCode;
		
		private System.Nullable<int> _HCResourceTypeCode;
		
		public vResources()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngName", DbType="NVarChar(500)")]
		public string EngName
		{
			get
			{
				return this._EngName;
			}
			set
			{
				if ((this._EngName != value))
				{
					this._EngName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseID", DbType="VarChar(100)")]
		public string BaseID
		{
			get
			{
				return this._BaseID;
			}
			set
			{
				if ((this._BaseID != value))
				{
					this._BaseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterCode", DbType="Int")]
		public System.Nullable<int> MasterCode
		{
			get
			{
				return this._MasterCode;
			}
			set
			{
				if ((this._MasterCode != value))
				{
					this._MasterCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCResourceTypeCode", DbType="Int")]
		public System.Nullable<int> HCResourceTypeCode
		{
			get
			{
				return this._HCResourceTypeCode;
			}
			set
			{
				if ((this._HCResourceTypeCode != value))
				{
					this._HCResourceTypeCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUserAccess")]
	public partial class vUserAccess
	{
		
		private System.Nullable<int> _UserCode;
		
		private string _Name;
		
		private System.Nullable<int> _AccessType;
		
		private string _ResName;
		
		private System.Nullable<int> _Ordering;
		
		private System.Nullable<int> _HCResourceTypeCode;
		
		private string _FirstName;
		
		private string _LastName;
		
		public vUserAccess()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessType", DbType="Int")]
		public System.Nullable<int> AccessType
		{
			get
			{
				return this._AccessType;
			}
			set
			{
				if ((this._AccessType != value))
				{
					this._AccessType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResName", DbType="VarChar(100)")]
		public string ResName
		{
			get
			{
				return this._ResName;
			}
			set
			{
				if ((this._ResName != value))
				{
					this._ResName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordering", DbType="Int")]
		public System.Nullable<int> Ordering
		{
			get
			{
				return this._Ordering;
			}
			set
			{
				if ((this._Ordering != value))
				{
					this._Ordering = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCResourceTypeCode", DbType="Int")]
		public System.Nullable<int> HCResourceTypeCode
		{
			get
			{
				return this._HCResourceTypeCode;
			}
			set
			{
				if ((this._HCResourceTypeCode != value))
				{
					this._HCResourceTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Address;
		
		private string _Email;
		
		private string _Password;
		
		private System.Nullable<int> _HCStudyFieldCode;
		
		private System.Nullable<int> _HCGenderCode;
		
		private string _ContactNumber;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _HCUserTypeCode;
		
		private string _PicFile;
		
		private EntitySet<UserGroups> _UserGroups;
		
		private EntitySet<UserAddresses> _UserAddresses;
		
		private EntitySet<UserTransactions> _UserTransactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnHCStudyFieldCodeChanging(System.Nullable<int> value);
    partial void OnHCStudyFieldCodeChanged();
    partial void OnHCGenderCodeChanging(System.Nullable<int> value);
    partial void OnHCGenderCodeChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnHCUserTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCUserTypeCodeChanged();
    partial void OnPicFileChanging(string value);
    partial void OnPicFileChanged();
    #endregion
		
		public Users()
		{
			this._UserGroups = new EntitySet<UserGroups>(new Action<UserGroups>(this.attach_UserGroups), new Action<UserGroups>(this.detach_UserGroups));
			this._UserAddresses = new EntitySet<UserAddresses>(new Action<UserAddresses>(this.attach_UserAddresses), new Action<UserAddresses>(this.detach_UserAddresses));
			this._UserTransactions = new EntitySet<UserTransactions>(new Action<UserTransactions>(this.attach_UserTransactions), new Action<UserTransactions>(this.detach_UserTransactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(200)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCStudyFieldCode", DbType="Int")]
		public System.Nullable<int> HCStudyFieldCode
		{
			get
			{
				return this._HCStudyFieldCode;
			}
			set
			{
				if ((this._HCStudyFieldCode != value))
				{
					this.OnHCStudyFieldCodeChanging(value);
					this.SendPropertyChanging();
					this._HCStudyFieldCode = value;
					this.SendPropertyChanged("HCStudyFieldCode");
					this.OnHCStudyFieldCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCGenderCode", DbType="Int")]
		public System.Nullable<int> HCGenderCode
		{
			get
			{
				return this._HCGenderCode;
			}
			set
			{
				if ((this._HCGenderCode != value))
				{
					this.OnHCGenderCodeChanging(value);
					this.SendPropertyChanging();
					this._HCGenderCode = value;
					this.SendPropertyChanged("HCGenderCode");
					this.OnHCGenderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(50)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this.OnContactNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactNumber = value;
					this.SendPropertyChanged("ContactNumber");
					this.OnContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCUserTypeCode", DbType="Int")]
		public System.Nullable<int> HCUserTypeCode
		{
			get
			{
				return this._HCUserTypeCode;
			}
			set
			{
				if ((this._HCUserTypeCode != value))
				{
					this.OnHCUserTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCUserTypeCode = value;
					this.SendPropertyChanged("HCUserTypeCode");
					this.OnHCUserTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile", DbType="NVarChar(200)")]
		public string PicFile
		{
			get
			{
				return this._PicFile;
			}
			set
			{
				if ((this._PicFile != value))
				{
					this.OnPicFileChanging(value);
					this.SendPropertyChanging();
					this._PicFile = value;
					this.SendPropertyChanged("PicFile");
					this.OnPicFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_UserGroups", Storage="_UserGroups", ThisKey="Code", OtherKey="UserCode")]
		public EntitySet<UserGroups> UserGroups
		{
			get
			{
				return this._UserGroups;
			}
			set
			{
				this._UserGroups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_UserAddresses", Storage="_UserAddresses", ThisKey="Code", OtherKey="UserCode")]
		public EntitySet<UserAddresses> UserAddresses
		{
			get
			{
				return this._UserAddresses;
			}
			set
			{
				this._UserAddresses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_UserTransaction", Storage="_UserTransactions", ThisKey="Code", OtherKey="UserCode")]
		public EntitySet<UserTransactions> UserTransactions
		{
			get
			{
				return this._UserTransactions;
			}
			set
			{
				this._UserTransactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserGroups(UserGroups entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_UserGroups(UserGroups entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
		
		private void attach_UserAddresses(UserAddresses entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_UserAddresses(UserAddresses entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
		
		private void attach_UserTransactions(UserTransactions entity)
		{
			this.SendPropertyChanging();
			entity.Users = this;
		}
		
		private void detach_UserTransactions(UserTransactions entity)
		{
			this.SendPropertyChanging();
			entity.Users = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ForgotPasswords")]
	public partial class ForgotPasswords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _UserCode;
		
		private string _GenKey;
		
		private System.Nullable<System.DateTime> _GenTime;
		
		private System.Nullable<bool> _Used;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnUserCodeChanging(System.Nullable<int> value);
    partial void OnUserCodeChanged();
    partial void OnGenKeyChanging(string value);
    partial void OnGenKeyChanged();
    partial void OnGenTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnGenTimeChanged();
    partial void OnUsedChanging(System.Nullable<bool> value);
    partial void OnUsedChanged();
    #endregion
		
		public ForgotPasswords()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenKey", DbType="VarChar(50)")]
		public string GenKey
		{
			get
			{
				return this._GenKey;
			}
			set
			{
				if ((this._GenKey != value))
				{
					this.OnGenKeyChanging(value);
					this.SendPropertyChanging();
					this._GenKey = value;
					this.SendPropertyChanged("GenKey");
					this.OnGenKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GenTime
		{
			get
			{
				return this._GenTime;
			}
			set
			{
				if ((this._GenTime != value))
				{
					this.OnGenTimeChanging(value);
					this.SendPropertyChanging();
					this._GenTime = value;
					this.SendPropertyChanged("GenTime");
					this.OnGenTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Used", DbType="Bit")]
		public System.Nullable<bool> Used
		{
			get
			{
				return this._Used;
			}
			set
			{
				if ((this._Used != value))
				{
					this.OnUsedChanging(value);
					this.SendPropertyChanging();
					this._Used = value;
					this.SendPropertyChanged("Used");
					this.OnUsedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vValidForgotPasswords")]
	public partial class vValidForgotPasswords
	{
		
		private int _Code;
		
		private string _GenKey;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _GenTime;
		
		private System.Nullable<bool> _Used;
		
		private System.Nullable<int> _UserCode;
		
		private string _FirstName;
		
		private string _LastName;
		
		public vValidForgotPasswords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenKey", DbType="VarChar(50)")]
		public string GenKey
		{
			get
			{
				return this._GenKey;
			}
			set
			{
				if ((this._GenKey != value))
				{
					this._GenKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GenTime
		{
			get
			{
				return this._GenTime;
			}
			set
			{
				if ((this._GenTime != value))
				{
					this._GenTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Used", DbType="Bit")]
		public System.Nullable<bool> Used
		{
			get
			{
				return this._Used;
			}
			set
			{
				if ((this._Used != value))
				{
					this._Used = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUserTransactions")]
	public partial class vUserTransactions
	{
		
		private int _Code;
		
		private System.Nullable<int> _UserCode;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _TransStatus;
		
		private System.Nullable<int> _Amount;
		
		private string _ChrgDate;
		
		private System.Nullable<int> _HCGenderCode;
		
		private string _BankName;
		
		private string _DigitalSignature;
		
		private string _UserIP;
		
		private string _Authority;
		
		private int _HCTransStatusCode;
		
		private System.Nullable<int> _HCPayReasonCode;
		
		private System.Nullable<int> _HCPayMethodCode;
		
		private string _PayMethod;
		
		private string _PayReason;
		
		private string _ItemType;
		
		private System.Nullable<int> _ItemCode;
		
		public vUserTransactions()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransStatus", DbType="NVarChar(500)")]
		public string TransStatus
		{
			get
			{
				return this._TransStatus;
			}
			set
			{
				if ((this._TransStatus != value))
				{
					this._TransStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
		public System.Nullable<int> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChrgDate", DbType="VarChar(10)")]
		public string ChrgDate
		{
			get
			{
				return this._ChrgDate;
			}
			set
			{
				if ((this._ChrgDate != value))
				{
					this._ChrgDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCGenderCode", DbType="Int")]
		public System.Nullable<int> HCGenderCode
		{
			get
			{
				return this._HCGenderCode;
			}
			set
			{
				if ((this._HCGenderCode != value))
				{
					this._HCGenderCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(500)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this._BankName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DigitalSignature", DbType="VarChar(20)")]
		public string DigitalSignature
		{
			get
			{
				return this._DigitalSignature;
			}
			set
			{
				if ((this._DigitalSignature != value))
				{
					this._DigitalSignature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserIP
		{
			get
			{
				return this._UserIP;
			}
			set
			{
				if ((this._UserIP != value))
				{
					this._UserIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Authority", DbType="VarChar(100)")]
		public string Authority
		{
			get
			{
				return this._Authority;
			}
			set
			{
				if ((this._Authority != value))
				{
					this._Authority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCTransStatusCode", DbType="Int NOT NULL")]
		public int HCTransStatusCode
		{
			get
			{
				return this._HCTransStatusCode;
			}
			set
			{
				if ((this._HCTransStatusCode != value))
				{
					this._HCTransStatusCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPayReasonCode", DbType="Int")]
		public System.Nullable<int> HCPayReasonCode
		{
			get
			{
				return this._HCPayReasonCode;
			}
			set
			{
				if ((this._HCPayReasonCode != value))
				{
					this._HCPayReasonCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPayMethodCode", DbType="Int")]
		public System.Nullable<int> HCPayMethodCode
		{
			get
			{
				return this._HCPayMethodCode;
			}
			set
			{
				if ((this._HCPayMethodCode != value))
				{
					this._HCPayMethodCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayMethod", DbType="NVarChar(500)")]
		public string PayMethod
		{
			get
			{
				return this._PayMethod;
			}
			set
			{
				if ((this._PayMethod != value))
				{
					this._PayMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayReason", DbType="NVarChar(500)")]
		public string PayReason
		{
			get
			{
				return this._PayReason;
			}
			set
			{
				if ((this._PayReason != value))
				{
					this._PayReason = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemType", DbType="NVarChar(50)")]
		public string ItemType
		{
			get
			{
				return this._ItemType;
			}
			set
			{
				if ((this._ItemType != value))
				{
					this._ItemType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="Int")]
		public System.Nullable<int> ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this._ItemCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vUserAddresses")]
	public partial class vUserAddresses
	{
		
		private int _Code;
		
		private int _UserCode;
		
		private string _FullName;
		
		private string _Address;
		
		private string _Province;
		
		private string _City;
		
		private string _CellPhone;
		
		private string _Tel;
		
		private string _PostalCode;
		
		private int _ProvinceCode;
		
		private int _CityCode;
		
		public vUserAddresses()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this._UserCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="NVarChar(100)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this._Province = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="NVarChar(50)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this._CellPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="VarChar(50)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this._PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceCode", DbType="Int NOT NULL")]
		public int ProvinceCode
		{
			get
			{
				return this._ProvinceCode;
			}
			set
			{
				if ((this._ProvinceCode != value))
				{
					this._ProvinceCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="Int NOT NULL")]
		public int CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this._CityCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserAddresses")]
	public partial class UserAddresses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _UserCode;
		
		private string _FullName;
		
		private string _CellPhone;
		
		private string _Tel;
		
		private int _ProvinceCode;
		
		private int _CityCode;
		
		private string _Address;
		
		private string _PostalCode;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnUserCodeChanging(int value);
    partial void OnUserCodeChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnCellPhoneChanging(string value);
    partial void OnCellPhoneChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnProvinceCodeChanging(int value);
    partial void OnProvinceCodeChanged();
    partial void OnCityCodeChanging(int value);
    partial void OnCityCodeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    #endregion
		
		public UserAddresses()
		{
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int NOT NULL")]
		public int UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="NVarChar(50)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this.OnCellPhoneChanging(value);
					this.SendPropertyChanging();
					this._CellPhone = value;
					this.SendPropertyChanged("CellPhone");
					this.OnCellPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceCode", DbType="Int NOT NULL")]
		public int ProvinceCode
		{
			get
			{
				return this._ProvinceCode;
			}
			set
			{
				if ((this._ProvinceCode != value))
				{
					this.OnProvinceCodeChanging(value);
					this.SendPropertyChanging();
					this._ProvinceCode = value;
					this.SendPropertyChanged("ProvinceCode");
					this.OnProvinceCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityCode", DbType="Int NOT NULL")]
		public int CityCode
		{
			get
			{
				return this._CityCode;
			}
			set
			{
				if ((this._CityCode != value))
				{
					this.OnCityCodeChanging(value);
					this.SendPropertyChanging();
					this._CityCode = value;
					this.SendPropertyChanged("CityCode");
					this.OnCityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="VarChar(50)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_UserAddresses", Storage="_Users", ThisKey="UserCode", OtherKey="Code", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.UserAddresses.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.UserAddresses.Add(this);
						this._UserCode = value.Code;
					}
					else
					{
						this._UserCode = default(int);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTransactions")]
	public partial class UserTransactions : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private System.Nullable<int> _UserCode;
		
		private int _HCTransStatusCode;
		
		private System.Nullable<int> _HCPayReasonCode;
		
		private System.Nullable<int> _HCPayMethodCode;
		
		private string _DigitalSignature;
		
		private System.Nullable<System.DateTime> _PayDate;
		
		private string _UserIP;
		
		private System.Nullable<int> _BankCode;
		
		private string _Authority;
		
		private string _Description;
		
		private System.Nullable<int> _Amount;
		
		private string _ItemType;
		
		private System.Nullable<int> _ItemCode;
		
		private string _CardNumberMasked;
		
		private System.Nullable<long> _RRN;
		
		private EntityRef<Users> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnUserCodeChanging(System.Nullable<int> value);
    partial void OnUserCodeChanged();
    partial void OnHCTransStatusCodeChanging(int value);
    partial void OnHCTransStatusCodeChanged();
    partial void OnHCPayReasonCodeChanging(System.Nullable<int> value);
    partial void OnHCPayReasonCodeChanged();
    partial void OnHCPayMethodCodeChanging(System.Nullable<int> value);
    partial void OnHCPayMethodCodeChanged();
    partial void OnDigitalSignatureChanging(string value);
    partial void OnDigitalSignatureChanged();
    partial void OnPayDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPayDateChanged();
    partial void OnUserIPChanging(string value);
    partial void OnUserIPChanged();
    partial void OnBankCodeChanging(System.Nullable<int> value);
    partial void OnBankCodeChanged();
    partial void OnAuthorityChanging(string value);
    partial void OnAuthorityChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAmountChanging(System.Nullable<int> value);
    partial void OnAmountChanged();
    partial void OnItemTypeChanging(string value);
    partial void OnItemTypeChanged();
    partial void OnItemCodeChanging(System.Nullable<int> value);
    partial void OnItemCodeChanged();
    partial void OnCardNumberMaskedChanging(string value);
    partial void OnCardNumberMaskedChanged();
    partial void OnRRNChanging(System.Nullable<long> value);
    partial void OnRRNChanged();
    #endregion
		
		public UserTransactions()
		{
			this._Users = default(EntityRef<Users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="Int")]
		public System.Nullable<int> UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					if (this._Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCTransStatusCode", DbType="Int NOT NULL")]
		public int HCTransStatusCode
		{
			get
			{
				return this._HCTransStatusCode;
			}
			set
			{
				if ((this._HCTransStatusCode != value))
				{
					this.OnHCTransStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._HCTransStatusCode = value;
					this.SendPropertyChanged("HCTransStatusCode");
					this.OnHCTransStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPayReasonCode", DbType="Int")]
		public System.Nullable<int> HCPayReasonCode
		{
			get
			{
				return this._HCPayReasonCode;
			}
			set
			{
				if ((this._HCPayReasonCode != value))
				{
					this.OnHCPayReasonCodeChanging(value);
					this.SendPropertyChanging();
					this._HCPayReasonCode = value;
					this.SendPropertyChanged("HCPayReasonCode");
					this.OnHCPayReasonCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCPayMethodCode", DbType="Int")]
		public System.Nullable<int> HCPayMethodCode
		{
			get
			{
				return this._HCPayMethodCode;
			}
			set
			{
				if ((this._HCPayMethodCode != value))
				{
					this.OnHCPayMethodCodeChanging(value);
					this.SendPropertyChanging();
					this._HCPayMethodCode = value;
					this.SendPropertyChanged("HCPayMethodCode");
					this.OnHCPayMethodCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DigitalSignature", DbType="VarChar(20)")]
		public string DigitalSignature
		{
			get
			{
				return this._DigitalSignature;
			}
			set
			{
				if ((this._DigitalSignature != value))
				{
					this.OnDigitalSignatureChanging(value);
					this.SendPropertyChanging();
					this._DigitalSignature = value;
					this.SendPropertyChanged("DigitalSignature");
					this.OnDigitalSignatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PayDate
		{
			get
			{
				return this._PayDate;
			}
			set
			{
				if ((this._PayDate != value))
				{
					this.OnPayDateChanging(value);
					this.SendPropertyChanging();
					this._PayDate = value;
					this.SendPropertyChanged("PayDate");
					this.OnPayDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserIP
		{
			get
			{
				return this._UserIP;
			}
			set
			{
				if ((this._UserIP != value))
				{
					this.OnUserIPChanging(value);
					this.SendPropertyChanging();
					this._UserIP = value;
					this.SendPropertyChanged("UserIP");
					this.OnUserIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankCode", DbType="Int")]
		public System.Nullable<int> BankCode
		{
			get
			{
				return this._BankCode;
			}
			set
			{
				if ((this._BankCode != value))
				{
					this.OnBankCodeChanging(value);
					this.SendPropertyChanging();
					this._BankCode = value;
					this.SendPropertyChanged("BankCode");
					this.OnBankCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Authority", DbType="VarChar(100)")]
		public string Authority
		{
			get
			{
				return this._Authority;
			}
			set
			{
				if ((this._Authority != value))
				{
					this.OnAuthorityChanging(value);
					this.SendPropertyChanging();
					this._Authority = value;
					this.SendPropertyChanged("Authority");
					this.OnAuthorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int")]
		public System.Nullable<int> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemType", DbType="NVarChar(50)")]
		public string ItemType
		{
			get
			{
				return this._ItemType;
			}
			set
			{
				if ((this._ItemType != value))
				{
					this.OnItemTypeChanging(value);
					this.SendPropertyChanging();
					this._ItemType = value;
					this.SendPropertyChanged("ItemType");
					this.OnItemTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemCode", DbType="Int")]
		public System.Nullable<int> ItemCode
		{
			get
			{
				return this._ItemCode;
			}
			set
			{
				if ((this._ItemCode != value))
				{
					this.OnItemCodeChanging(value);
					this.SendPropertyChanging();
					this._ItemCode = value;
					this.SendPropertyChanged("ItemCode");
					this.OnItemCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNumberMasked", DbType="VarChar(50)")]
		public string CardNumberMasked
		{
			get
			{
				return this._CardNumberMasked;
			}
			set
			{
				if ((this._CardNumberMasked != value))
				{
					this.OnCardNumberMaskedChanging(value);
					this.SendPropertyChanging();
					this._CardNumberMasked = value;
					this.SendPropertyChanged("CardNumberMasked");
					this.OnCardNumberMaskedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RRN", DbType="BigInt")]
		public System.Nullable<long> RRN
		{
			get
			{
				return this._RRN;
			}
			set
			{
				if ((this._RRN != value))
				{
					this.OnRRNChanging(value);
					this.SendPropertyChanging();
					this._RRN = value;
					this.SendPropertyChanged("RRN");
					this.OnRRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_UserTransaction", Storage="_Users", ThisKey="UserCode", OtherKey="Code", IsForeignKey=true)]
		public Users Users
		{
			get
			{
				return this._Users.Entity;
			}
			set
			{
				Users previousValue = this._Users.Entity;
				if (((previousValue != value) 
							|| (this._Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users.Entity = null;
						previousValue.UserTransactions.Remove(this);
					}
					this._Users.Entity = value;
					if ((value != null))
					{
						value.UserTransactions.Add(this);
						this._UserCode = value.Code;
					}
					else
					{
						this._UserCode = default(Nullable<int>);
					}
					this.SendPropertyChanged("Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_GetMultipleAccessResult
	{
		
		private System.Nullable<int> _GroupCode;
		
		private int _ResourceCode;
		
		public sp_GetMultipleAccessResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="Int")]
		public System.Nullable<int> GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this._GroupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceCode", DbType="Int NOT NULL")]
		public int ResourceCode
		{
			get
			{
				return this._ResourceCode;
			}
			set
			{
				if ((this._ResourceCode != value))
				{
					this._ResourceCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
