<?xml version="1.0" encoding="utf-8"?><Database Name="Ranjbaran" Class="UsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Ranjbaran;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RanjbaranConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vUsers" Member="vUsers">
    <Type Name="vUsers">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudyFieldName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GenderName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccessGroups" Member="AccessGroups">
    <Type Name="AccessGroups">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="AccessGroups_UserGroups" Member="UserGroups" ThisKey="Code" OtherKey="GroupCode" Type="UserGroups" />
      <Association Name="AccessGroups_GroupResources" Member="GroupResources" ThisKey="Code" OtherKey="GroupCode" Type="GroupResources" />
    </Type>
  </Table>
  <Table Name="dbo.Resources" Member="Resources">
    <Type Name="Resources">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EngName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HCResourceTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MasterCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditPath" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BaseID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BasicAccessType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ordering" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Resources_Resources" Member="Resources1" ThisKey="Code" OtherKey="MasterCode" Type="Resources" />
      <Association Name="Resources_GroupResources" Member="GroupResources" ThisKey="Code" OtherKey="ResourceCode" Type="GroupResources" />
      <Association Name="Resources_Resources" Member="Resource1" ThisKey="MasterCode" OtherKey="Code" Type="Resources" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroups" Member="UserGroups">
    <Type Name="UserGroups">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AccessGroups_UserGroups" Member="AccessGroups" ThisKey="GroupCode" OtherKey="Code" Type="AccessGroups" IsForeignKey="true" />
      <Association Name="Users_UserGroups" Member="Users" ThisKey="UserCode" OtherKey="Code" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupResources" Member="GroupResources">
    <Type Name="GroupResources">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResourceCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccessType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AccessGroups_GroupResources" Member="AccessGroups" ThisKey="GroupCode" OtherKey="Code" Type="AccessGroups" IsForeignKey="true" />
      <Association Name="Resources_GroupResources" Member="Resources" ThisKey="ResourceCode" OtherKey="Code" Type="Resources" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.vAccessGroups" Member="vAccessGroups">
    <Type Name="vAccessGroups">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vGroupResources" Member="vGroupResources">
    <Type Name="vGroupResources">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResourceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ResourceCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccessType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vUserGroups" Member="vUserGroups">
    <Type Name="vUserGroups">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vResources" Member="vResources">
    <Type Name="vResources">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EngName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BaseID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MasterCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCResourceTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vUserAccess" Member="vUserAccesses">
    <Type Name="vUserAccess">
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AccessType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Ordering" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCResourceTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HCStudyFieldCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCGenderCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HCUserTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Users_UserGroups" Member="UserGroups" ThisKey="Code" OtherKey="UserCode" Type="UserGroups" />
      <Association Name="Users_UserAddresses" Member="UserAddresses" ThisKey="Code" OtherKey="UserCode" Type="UserAddresses" />
      <Association Name="Users_UserTransaction" Member="UserTransactions" ThisKey="Code" OtherKey="UserCode" Type="UserTransactions" />
    </Type>
  </Table>
  <Table Name="dbo.ForgotPasswords" Member="ForgotPasswords">
    <Type Name="ForgotPasswords">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GenKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GenTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Used" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vValidForgotPasswords" Member="vValidForgotPasswords">
    <Type Name="vValidForgotPasswords">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GenKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GenTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Used" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vUserTransactions" Member="vUserTransactions">
    <Type Name="vUserTransactions">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransStatus" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChrgDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HCGenderCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DigitalSignature" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UserIP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Authority" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HCTransStatusCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HCPayReasonCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCPayMethodCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayMethod" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PayReason" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ItemType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vUserAddresses" Member="vUserAddresses">
    <Type Name="vUserAddresses">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CellPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProvinceCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserAddresses" Member="UserAddresses">
    <Type Name="UserAddresses">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CellPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProvinceCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Users_UserAddresses" Member="Users" ThisKey="UserCode" OtherKey="Code" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTransactions" Member="UserTransactions">
    <Type Name="UserTransactions">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCTransStatusCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HCPayReasonCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCPayMethodCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DigitalSignature" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PayDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserIP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BankCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Authority" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNumberMasked" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RRN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Users_UserTransaction" Member="Users" ThisKey="UserCode" OtherKey="Code" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetMultipleAccess" Method="sp_GetMultipleAccess">
    <Parameter Name="paramAccessTypeCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="paramGroupCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="paramMasterCode" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetMultipleAccessResult">
      <Column Name="GroupCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResourceCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>