//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:2.0.50727.3053
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System;
using System.Xml;
using System.Collections.Generic;
using System.Threading;

//
// This source code was auto-generated by xsd, Version=2.0.50727.42.
//

namespace YahooWeather
{
    public class Helper
    {
        public static bool IsLoading = false;
        public static Thread DThread;

        private static string _URL = "http://weather.yahooapis.com/forecastrss?p=IRXX0018&u=c";
        public static string URL
        {
            get { return _URL; }
            set { _URL = value; }
        }

        public static DateTime LastUpdate { get; set; }

        public static rss Data { get; set; }

        public static int hour
        {
            get
            {
                return Math.Abs(Convert.ToInt32((LastUpdate - DateTime.Now).TotalHours));
            }
        }

        public static void GoDownloader()
        {
            if (!Helper.IsLoading)
            {
                try
                {
                    ThreadStart d_RunThread = new ThreadStart(DoCommands);
                    DThread = new Thread(d_RunThread);
                    DThread.Priority = ThreadPriority.Normal;
                    DThread.Name = "Download Yahoo Data";
                    DThread.Start();
                    Helper.IsLoading = true;
                }
                catch (Exception ex)
                {
                }
            }
        }

        private static void DoCommands()
        {
            try
            {
                bool Result = false;
                rss NewData = null;
                XmlSerializer rd = new XmlSerializer(typeof(rss));
                try
                {
                    using (XmlReader reader = XmlReader.Create(URL))
                    {
                        NewData = (rss)rd.Deserialize(reader);
                        Result = true;
                    }
                }
                catch (Exception ex)
                {
                }

                if (Result)
                {
                    Helper.Data = NewData;
                    Helper.LastUpdate = DateTime.Today;
                }
            }
            catch (Exception ex)
            {
            }
            Helper.IsLoading = false;
        }

        public static bool Get()
        {
            if ((hour >= 1) && !IsLoading)
            {
                GoDownloader();
            }
            return true;
        }

        public static Dictionary<int, string> ImageMaps = new Dictionary<int, string>
{
{0, "tstorm3.png"},{1, "tstorm3.png"},{2, "tstorm3.png"},{3, "tstorm3.png"},
{4, "tstorm3.png"},{5, "sleet.png"},{6, "snow4.png"},{7, "sleet.png"},
{8, "snow5.png"},{9, "snow5.png"},{10, "sleet.png"},{11, "shower3.png"},
{12, "shower3.png"},{13, "snow4.png"},{14, "snow4.png"},{15, "snow4.png"},
{16, "snow4.png"},{17, "tstorm3.png"},{18, "sleet.png"},{19, "mist.png"},
{20, "fog.png"},{21, "fog.png"},{22, "fog.png"},{23, "1211810703.png"},
{24, "1211810703.png"},{25, "1211810657.png"},{26, "cloudy5.png"},{27, "cloudy4_night.png"},
{28, "cloudy4.png"},{29, "cloudy3_night.png"},{30, "cloudy3.png"},{31, "sunny_night.png"},
{32, "sunny.png"},{33, "sunny_night.png"},{34, "sunny.png"},{35, "tstorm3.png"},
{36, "sunny.png"},{37, "tstorm3.png"},{38, "tstorm3.png"},{39, "tstorm3.png"},
{40, "light_rain.png"},{41, "snow5.png"},{42, "snow4.png"},{43, "snow5.png"},
{44, "cloudy5.png"},{45, "tstorm3.png"},{46, "sleet.png"},{47, "tstorm3.png"}, {3200,"dunno.png"}
};

        public static Dictionary<int, string> NameMaps = new Dictionary<int, string> {
{0, "طوفانی"},{1, "طوفانی"},{2, "طوفانی"},{3, "طوفانی"},
{4, "طوفانی"},{5, "باران و برف"},{6, "باران و برف"},{7, "باران و برف"},
{8, "تگرگ ریز"},{9, "باران و برف ریز"},{10, "تگرگ"},{11, "بارانی"},
{12, "بارانی"},{13, "باد و برف"},{14, "کمی برفی"},{15, "برف ریز"},
{16, "برفی"},{17, "باد"},{18, "گرد و غبار"},{19, "گرد و غبار"},
{20, "غبار آلود"},{21, "غبار آلود"},{22, "مه"},{23, "باد"},
{24, "باد"},{25, "یخبندان"},{26, "ابری"},{27, "خیلی ابری"},
{28, "خیلی ابری"},{29, "ابری"},{30, "ابری"},{31, "صاف"},
{32, "صاف"},{33, "صاف"},{34, "آفتابی"},{35, "باد و باران"},
{36, "گرم و آفتابی"},{37, "طوفانی"},{38, "طوفانی"},{39, "بارانی"},
{40, "کمی بارانی"},{41, "برفی"},{42, "کمی برفی"},{43, "برفی"},
{44, "ابری"},{45, "طوفانی"},{46, "باد و باران"},{47, "باد و باران"}, {3200,"نامعلوم"}
};

        public static string BuildHTML()
        {
            string result = "";
            if (Get() && YahooWeather.Helper.Data != null)
            {
                int id = Convert.ToInt32(YahooWeather.Helper.Data.channel.item.condition.code);

                string img = YahooWeather.Helper.ImageMaps[id];
                string txt = YahooWeather.Helper.NameMaps[id];

                result = "<div style=\"text-align:center;direction:rtl;\"><img style=\"width:48px;height:48px\" src=\"/Images/weather/" + img + "\" /><br />";
                result += "دما: " + Tools.ChangeEnc( YahooWeather.Helper.Data.channel.item.condition.temp) + " سانتیگراد<br />";
                result += "وضعیت هوا: " + txt + "<br />";
                result += "<table style=\"width:99%\"><tr><td>&nbsp;</td><td>امروز</td><td>فردا</td></tr>";
                result += "<tr><td>حداقل</td><td>" + Tools.ChangeEnc(YahooWeather.Helper.Data.channel.item.forecast[0].low) + "</td><td>"
                + Tools.ChangeEnc(YahooWeather.Helper.Data.channel.item.forecast[1].low) + "</td></tr>";
                result += "<tr><td>حداکثر</td><td>" + Tools.ChangeEnc(YahooWeather.Helper.Data.channel.item.forecast[0].high) + "</td><td>"
                + Tools.ChangeEnc(YahooWeather.Helper.Data.channel.item.forecast[1].high) + "</td></tr>";
                result += "</table></div>";
            }
            return result;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "")]
    public partial class rss
    {

        private rssChannel channelField;

        private decimal versionField;

        /// <remarks/>
        public rssChannel channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rssChannel
    {

        private string titleField;

        private string linkField;

        private string descriptionField;

        private string languageField;

        private string lastBuildDateField;

        private string ttlField;

        private location locationField;

        private units unitsField;

        private wind windField;

        private atmosphere atmosphereField;

        private astronomy astronomyField;

        private rssChannelImage imageField;

        private rssChannelItem itemField;

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string lastBuildDate
        {
            get
            {
                return this.lastBuildDateField;
            }
            set
            {
                this.lastBuildDateField = value;
            }
        }

        /// <remarks/>
        public string ttl
        {
            get
            {
                return this.ttlField;
            }
            set
            {
                this.ttlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
        public location location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
        public units units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
        public wind wind
        {
            get
            {
                return this.windField;
            }
            set
            {
                this.windField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
        public atmosphere atmosphere
        {
            get
            {
                return this.atmosphereField;
            }
            set
            {
                this.atmosphereField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
        public astronomy astronomy
        {
            get
            {
                return this.astronomyField;
            }
            set
            {
                this.astronomyField = value;
            }
        }

        /// <remarks/>
        public rssChannelImage image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        public rssChannelItem item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    public partial class location
    {

        private string cityField;

        private string regionField;

        private string countryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    public partial class units
    {

        private string temperatureField;

        private string distanceField;

        private string pressureField;

        private string speedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string temperature
        {
            get
            {
                return this.temperatureField;
            }
            set
            {
                this.temperatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pressure
        {
            get
            {
                return this.pressureField;
            }
            set
            {
                this.pressureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string speed
        {
            get
            {
                return this.speedField;
            }
            set
            {
                this.speedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    public partial class wind
    {

        private string chillField;

        private string directionField;

        private decimal speedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chill
        {
            get
            {
                return this.chillField;
            }
            set
            {
                this.chillField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal speed
        {
            get
            {
                return this.speedField;
            }
            set
            {
                this.speedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    public partial class atmosphere
    {

        private string humidityField;

        private string visibilityField;

        private decimal pressureField;

        private string risingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string humidity
        {
            get
            {
                return this.humidityField;
            }
            set
            {
                this.humidityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string visibility
        {
            get
            {
                return this.visibilityField;
            }
            set
            {
                this.visibilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pressure
        {
            get
            {
                return this.pressureField;
            }
            set
            {
                this.pressureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rising
        {
            get
            {
                return this.risingField;
            }
            set
            {
                this.risingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    public partial class astronomy
    {

        private string sunriseField;

        private string sunsetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sunrise
        {
            get
            {
                return this.sunriseField;
            }
            set
            {
                this.sunriseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sunset
        {
            get
            {
                return this.sunsetField;
            }
            set
            {
                this.sunsetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rssChannelImage
    {

        private string titleField;

        private string widthField;

        private string heightField;

        private string linkField;

        private string urlField;

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        public string height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        public string link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rssChannelItem
    {

        private string titleField;

        private decimal latField;

        private decimal longField;

        private string linkField;

        private string pubDateField;

        private condition conditionField;

        private string descriptionField;

        private forecast[] forecastField;

        private rssChannelItemGuid guidField;

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#")]
        public decimal lat
        {
            get
            {
                return this.latField;
            }
            set
            {
                this.latField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#")]
        public decimal @long
        {
            get
            {
                return this.longField;
            }
            set
            {
                this.longField = value;
            }
        }

        /// <remarks/>
        public string link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        /// <remarks/>
        public string pubDate
        {
            get
            {
                return this.pubDateField;
            }
            set
            {
                this.pubDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
        public condition condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("forecast", Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
        public forecast[] forecast
        {
            get
            {
                return this.forecastField;
            }
            set
            {
                this.forecastField = value;
            }
        }

        /// <remarks/>
        public rssChannelItemGuid guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    public partial class condition
    {

        private string textField;

        private string codeField;

        private string tempField;

        private string dateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string temp
        {
            get
            {
                return this.tempField;
            }
            set
            {
                this.tempField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.weather.yahoo.com/ns/rss/1.0")]
    public partial class forecast
    {

        private string dayField;

        private string dateField;

        private string lowField;

        private string highField;

        private string textField;

        private string codeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string low
        {
            get
            {
                return this.lowField;
            }
            set
            {
                this.lowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string high
        {
            get
            {
                return this.highField;
            }
            set
            {
                this.highField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rssChannelItemGuid
    {

        private bool isPermaLinkField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isPermaLink
        {
            get
            {
                return this.isPermaLinkField;
            }
            set
            {
                this.isPermaLinkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}
